# Generated by Django 3.1.1 on 2021-11-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_column='s', max_length=255)),
                ('target', models.CharField(db_column='o', max_length=255)),
                ('name', models.CharField(db_column='p', max_length=255)),
                ('des', models.CharField(db_column='des', max_length=255)),
            ],
            options={
                'db_table': 'graph',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='entity', max_length=255)),
                ('des', models.CharField(db_column='des', max_length=255)),
                ('symbolsize', models.IntegerField(db_column='symbolsize')),
                ('category', models.IntegerField(db_column='depth')),
            ],
            options={
                'db_table': 'node',
                'managed': True,
            },
        ),
    ]
