# Generated by Django 3.1.1 on 2021-11-02 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasdaq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodes',
            old_name='symbolsize',
            new_name='symbolSize',
        ),
    ]
